repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        files: '(\.(go|md|sh|yml|yaml|json|ini|rst)|Dockerfile.*)$'
        exclude: '^vendor/'
      - id: trailing-whitespace
        files: '(\.(go|md|sh|yml|yaml|json|ini|rst)|Dockerfile.*)$'
        exclude: '^vendor/'
      - id: check-yaml
        exclude: '^vendor/'
      - id: check-json
        exclude: '^vendor/'

  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: golangci-lint
        args: ['-v', './...']
